import React, { useEffect, useState } from "react";
import API from "../services/api";
import { authHeaders } from "../services/auth";

const blank = { enabled: false, image_url: "", secondary_image_url: "", text_value: "", position: "bottom-right", opacity: 45, preview_enabled: true, download_enabled: true };
export default function WatermarkPanel({ endpoint = "/watermark/settings", title = "Default watermark" }) {
  const [value, setValue] = useState(blank); const [notice, setNotice] = useState("");
  useEffect(() => { API.get(endpoint, { headers: authHeaders() }).then(({ data }) => setValue({ ...blank, ...data })).catch(() => setNotice("Could not load watermark settings.")); }, [endpoint]);
  const set = (name, next) => setValue((old) => ({ ...old, [name]: next }));
  const upload = async (event) => { const file = event.target.files?.[0]; if (!file) return; const body = new FormData(); body.append("file", file); try { const { data } = await API.post("/watermark/upload", body, { headers: authHeaders() }); set("image_url", data.image_url); setNotice("Logo uploaded. Save settings to apply it."); } catch (err) { setNotice(err.response?.data?.detail || "Could not upload logo."); } finally { event.target.value = ""; } };
  const save = async (e) => { e.preventDefault(); try { await API.put(endpoint, value, { headers: authHeaders() }); setNotice("Watermark settings saved."); } catch (err) { setNotice(err.response?.data?.detail || "Could not save watermark settings."); } };
  return <form className="watermark-settings" onSubmit={save}><div className="settings-heading"><div><p className="eyebrow">BRANDING</p><h2>{title}</h2><p className="muted">Add your logo, sponsor logo, or text to guest previews.</p></div><label className="toggle"><input type="checkbox" checked={value.enabled} onChange={(e) => set("enabled", e.target.checked)} /> Enable</label></div><div className="watermark-fields"><label>Logo image URL<input type="url" value={value.image_url || ""} onChange={(e) => set("image_url", e.target.value)} /></label><label>Upload your logo<input type="file" accept="image/jpeg,image/png,image/webp" onChange={upload} /></label><label>Sponsor logo URL<input type="url" value={value.secondary_image_url || ""} onChange={(e) => set("secondary_image_url", e.target.value)} /></label><label>Watermark text<input maxLength="120" value={value.text_value || ""} onChange={(e) => set("text_value", e.target.value)} placeholder="Copyright 2026 Your Studio" /></label><label>Placement<select value={value.position} onChange={(e) => set("position", e.target.value)}><option value="bottom-right">Bottom right</option><option value="bottom-left">Bottom left</option><option value="top-right">Top right</option><option value="top-left">Top left</option><option value="center">Center</option><option value="tiled">Tiled</option></select></label><label>Transparency ({value.opacity}%)<input type="range" min="10" max="90" value={value.opacity} onChange={(e) => set("opacity", Number(e.target.value))} /></label></div><div className="check-row"><label><input type="checkbox" checked={value.preview_enabled} onChange={(e) => set("preview_enabled", e.target.checked)} /> Watermark previews</label><label><input type="checkbox" checked={value.download_enabled} onChange={(e) => set("download_enabled", e.target.checked)} /> Watermark downloads</label></div><button className="primary-button">Save watermark settings</button>{notice && <p className={notice.includes("saved") ? "success-message" : "form-error"}>{notice}</p>}</form>;
}
