import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import API from "../services/api";

export default function PublicGuestGallery() {
  const { token } = useParams();
  const [data, setData] = useState(null); const [error, setError] = useState("");
  const [selfie, setSelfie] = useState(null); const [matches, setMatches] = useState(null); const [searching, setSearching] = useState(false);
  useEffect(() => { API.get(`/public/events/${token}`).then(({ data }) => setData(data)).catch((err) => setError(err.response?.data?.detail || "This gallery is unavailable.")); }, [token]);
  const find = async (event) => { event.preventDefault(); if (!selfie) { setError("Choose a clear selfie first."); return; } setSearching(true); setError(""); const body = new FormData(); body.append("files", selfie); try { const { data: result } = await API.post(`/public/events/${token}/search`, body); setMatches(result.matched_photos || []); } catch (err) { setError(err.response?.data?.detail || "We could not search your photos. Please try again."); } finally { setSearching(false); } };
  if (error && !data) return <main className="guest-shell"><div className="guest-empty"><h1>Gallery unavailable</h1><p>{error}</p></div></main>;
  if (!data) return <main className="guest-shell"><p>Loading your gallery...</p></main>;
  return <main className="guest-shell"><header className="guest-header"><a className="brand" href="/">Lens<span>Link</span></a><span>Shared gallery</span></header><section className="guest-intro"><p className="eyebrow">{data.event.event_date}</p><h1>{data.event.name}</h1><p>{data.event.description || "All the moments from this event, in one place."}</p><a className="find-button" href="#find-photos">Find My Photos</a></section><section id="find-photos" className="guest-find-panel"><h2>Find your photos</h2><p>Upload one clear selfie. No sign-in is required.</p><form onSubmit={find}><input type="file" accept="image/jpeg,image/png,image/webp" onChange={(e) => setSelfie(e.target.files?.[0] || null)} /><button className="primary-button" disabled={searching}>{searching ? "Searching..." : "Find My Photos"}</button></form>{error && <p className="form-error">{error}</p>}{matches && <div><h3>{matches.length ? `We found ${matches.length} photo${matches.length === 1 ? "" : "s"}` : "No matches yet"}</h3><div className="guest-photo-grid">{matches.map((photo) => <article className="guest-photo" key={photo.image_url}><img src={photo.image_url} alt="Your matched event photo" /><a className="guest-download" href={photo.image_url.replace("/upload/", "/upload/fl_attachment/")} download>Download photo</a></article>)}</div></div>}</section>{data.albums.map((album) => <section className="guest-album" key={album.id}><h2>{album.name}</h2>{album.description && <p className="muted">{album.description}</p>}<div className="guest-photo-grid">{album.photos.map((photo) => <article className="guest-photo" key={photo.id}><img src={photo.preview_url} alt={photo.title || "Event photograph"} /><a className="guest-download" href={photo.download_url} download>Download preview</a></article>)}</div></section>)}</main>;
}
